cors:
  originPatterns: http://localhost:3000,http://localhost:8080,http://localhost:8081
security:
  jwt:
    token:
      secrete-key: 53cr37
      expire-lenght: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api-restful?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none

spring-doc:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true